[tool.poetry]
name = "dtone-python"
version = "0.1.0"
description = ""
authors = ["nathanbegbie <nathanbegbie@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
