name: Deploy Docs To GH Pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # check out sources that will be used for autodocs, plus readme
    steps:
      - uses: actions/checkout@v1

      # didn't need to change anything here, but had to add sphinx.ext.githubpages
      # to my conf.py extensions list. that fixes the broken uploads
      - name: Building documentation
        run: |
          pip install invoke
          pip install -r requirements-doc.txt
          invoke makedocs
          # sphinx-build docs public -b dirhtml

      # still need to build and set the PAT to get a rebuild on the pages job,
      # apart from that quite clean and nice
      - name: github pages deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: docs/_build
        with:
          emptyCommits: false
